import type { Metadata } from 'next';
import '@/styles/globals.css';
import localFont from 'next/font/local';
import { cn } from '@/lib/utils';
import Providers from '@/components/providers';
import SiteHeader from '@/components/site-header';

const fontRegularSans = localFont({
  src: '../assets/fonts/Inter-Regular.ttf',
  variable: '--font-sans',
});

const fontBoldSans = localFont({
  src: '../assets/fonts/Inter-Regular.ttf',
  variable: '--font-BoldSans',
});

const fontHeading = localFont({
  src: '../assets/fonts/CalSans-SemiBold.woff2',
  variable: '--font-heading',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
interface RootLayoutProps {
  children: React.ReactNode;
}
export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          'min-h-screen antialiased font-sans_regular',
          fontRegularSans.variable,
          fontBoldSans.variable,
          fontHeading.variable
        )}
      >
        <Providers>
          <div className="relative flex min-h-screen flex-col">
            <SiteHeader />
            {/* TODO:Create SiteBlobs */}
            <div className="flex-1">{children}</div>
            {/* TODO: Create SiteFooter  */}
          </div>
        </Providers>
      </body>
    </html>
  );
}
