import type { Metadata } from 'next';
import '@/styles/globals.css';
import localFont from 'next/font/local';
import { cn } from '@/lib/utils';

const fontRegularSans = localFont({
  src: '../assets/fonts/Inter-Regular.ttf',
  variable: '--font-sans',
});

const fontBoldSans = localFont({
  src: '../assets/fonts/Inter-Regular.ttf',
  variable: '--font-BoldSans',
});

const fontHeading = localFont({
  src: '../assets/fonts/CalSans-SemiBold.woff2',
  variable: '--font-heading',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
interface RootLayoutProps {
  children: React.ReactNode;
}
export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          'min-h-screen antialiased font-sans_regular',
          fontRegularSans.variable,
          fontBoldSans.variable,
          fontHeading.variable
        )}
      >
        {children}
      </body>
    </html>
  );
}
